server:
  port: 10010
  
spring:
  redis:
    host: 58.213.91.96
    port: 29012

ignore:
  urls:
    - /**/*.css
    - /oauth/**
    - /auth/oauth/**
    - /actuator/**
    - /hystrix/**
    - /swagger-resource/**
    - /swagger-ui.html/**
    - /webjars/**
    - /swagger-resources/**
    - /v2/api-docs 
    - /rscLogin
    - /captcha.jpg